ALTER TABLE users
  ADD COLUMN IF NOT EXISTS dob            DATE,
  ADD COLUMN IF NOT EXISTS pincode        TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS state          TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS district       TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS taluk          TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS reference_name TEXT NOT NULL DEFAULT '';
