ALTER TABLE users
  ADD COLUMN IF NOT EXISTS account_holder_name TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS bank_name           TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS account_number      TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS ifsc_code           TEXT NOT NULL DEFAULT '';
